name: HTML Check

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Requried will all actions
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@<latest version>
      with:
        name: log
        path: logs/CI-Log.log